spring:
  application:
    name: jxservice
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: restart_context
test:
  message: "Base Test Message"
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    restart:
      enabled: true
